### ISSUE TITLE
Current release is very old, can't join chain. Suggest Rebuilding package now that there are official docker releases by the core  devs.

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DAppNodePackage-zcash#13]
This package hasn't worked in many months, due to a breaking version change since the last update.  I was looking at the code closer and saw that this is done from custom built docker images, and the docker file isnt instructions to run an upstream docker image but to apt-get install the package etc.  I assume this was because ZCash didnt have maintained docker images at the time, but they do now [here](https://hub.docker.com/r/electriccoinco/zcashd/tags). I don't think this is really a priority package for many people but I'd like to try to bring it back as an option, the more working packages the better regardless of how popular they are.  Which is why i suggest that I try to rebuild this package from scratch (in my own forked repo of course) using the zcash docker images as the source, and having this repo for ENV values and parameters, and other dappnode DNP repos for how to build the rest properly.  Please et me know if theres a reason i shouldnt even try this.

**Comment by dapplion** [comment]
@alexpeterson91 Thank you so much for stepping in! We would gladly review, test and release a new version proposed for you. Feel free to open a PR to this repo changing as much as necessary. We are very aligned with ZCash and the only reason for the lack of support is purely resource constraint. Excited to see this package fully usable soon!
